// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Record struct {
	ID       string `json:"id"`
	Location string `json:"location"`
	Time     string `json:"time"`
	Set      string `json:"set"`
}

type SearchAResult struct {
	Location string `json:"location"`
	Time     string `json:"time"`
}
